[args]
LeftSegments = [         # List of segment to load in left prompt.
    "user",
    "host",
    # "ssh",
    # "perms",
    "pwd",
    "git",
    # "jobs",
    "nl",
    "root",
    "exit",
]
RightSegments = [        # List of segment to load in rigt prompt.
    "git",
    "jobs"
]
GitMode = "simple"       # Git segment mode. Valid are "fancy", "simple"
CwdMode = "simple"       # Path segment mode. Valid are "fancy", "simple"
CwdMaxDepth = 0          # Max amount of subdirectory to show in path segment
MaxWidthRatio    = 0     # Maximum width percentage of terminal occupied by prompt
MaxSegmentWidth  = 0     # Minimum width of a segment
ColorizeHostname = false # Colorize the hostname with a hash of itself
NumericExitCodes = false # Show numeric exit status instead of description
ShortenGKENames = false  # Shortens names for GKE Kube clusters
IgnoreRepos = ""         # List of absolute path that will be ignored by the git segment
Duration    = ""         # Number of wall-clock seconds elapsed for the previous command
PathAliases = [
    {"some/random/path" = "shortcut"},
    {"Desktop" = "Desktaupe"}
]


[symbols]
Lock           = ""
Network        = ""
Separator      = ""
RSeparator     = ""
SeparatorThin  = ""
RSeparatorThin = ""
GitBranch      = ""
GitDetached    = "➦"
GitAhead       = "⬆"
GitBehind      = "⬇"
GitStaged      = "✔"
GitNotStaged   = "✎"
GitConflicted  = "✼"
GitUntracked   = "…"


[theme]
separator         = { fg =   15 }
username          = { fg =  234, bg =  250}
username_root     = { fg =  234, bg =  198}
hostname          = { fg =  234, bg =  252}
home              = { fg =   30, bg =   15}
path              = { fg =  234, bg =  254}
cwd               = { fg =  236, bg =  254}
readonly          = { fg =  124, bg =  253}
ssh               = { fg =  166, bg =  254}
docker_machine    = { fg =   55, bg =  177}
kube_cluster      = { fg =  117, bg =   26}
kube_namespace    = { fg =  170, bg =   17}
dot_env           = { fg =   15, bg =   55}
# aws              = { fg =    ?, bg = ?}
repo_clean        = { fg =  232, bg =  230}
repo_dirty        = { fg =  232, bg =  223}
jobs              = { fg =  238, bg =   39}
cmd_passed        = { fg =   18, bg =    7}
cmd_failed        = { fg =  254, bg =  124}
svn_changes       = { fg =  148, bg =   22}
git_ahead         = { fg =  240, bg =  250}
git_behind        = { fg =  240, bg =  251}
git_staged        = { fg =   22, bg =   15}
git_not_staged    = { fg =  130, bg =   15}
git_untracked     = { fg =   52, bg =   15}
git_conflicted    = { fg =    9, bg =   15}
git_stashed       = { fg =   15, bg =   20}
virtual_env       = { fg =   35, bg =  254}
virtual_go        = { fg =   35, bg =  254}
perlbrew          = { fg =   20, bg =   15}
TFWs              = { fg =   15, bg =   26}
time              = { fg =  236, bg =  15}
# shell_var         = { fg =    ?, bg = ?}
# node              = { fg =    ?, bg = ?}
load              = { fg =   15, bg =   22}
nix_shell         = { fg =   69, bg =  254}
# duration          = { fg =    ?, bg = ?}
