[args]
LeftSegments = [         # List of segment to load in left prompt.
    "user",
    "host",
    # "ssh",
    # "perms",
    "pwd",
    "git",
    # "jobs",
    "nl",
    "root",
    "exit"
]
RightSegments = [        # List of segment to load in rigt prompt.
    "git",
    "jobs"
]
GitMode = "simple"       # Git segment mode. Valid are "fancy", "simple"
CwdMode = "simple"       # Path segment mode. Valid are "fancy", "simple"
CwdMaxDepth = 0          # Max amount of subdirectory to show in path segment
MaxWidthRatio    = 0     # Maximum width percentage of terminal occupied by prompt
MaxSegmentWidth  = 0     # Minimum width of a segment
ColorizeHostname = false # Colorize the hostname with a hash of itself
NumericExitCodes = false # Show numeric exit status instead of description
ShortenGKENames = false  # Shortens names for GKE Kube clusters
IgnoreRepos = ""         # List of absolute path that will be ignored by the git segment
Duration    = ""         # Number of wall-clock seconds elapsed for the previous command
PathAliases = [
    {"some/random/path" = "shortcut"},
    {"Documents" = "cheese"}
]


[symbols]
Lock           = ""
Network        = ""
Separator      = ""
RSeparator     = ""
SeparatorThin  = ""
RSeparatorThin = ""
GitBranch      = ""
GitDetached    = "➦"
GitAhead       = "⬆"
GitBehind      = "⬇"
GitStaged      = "✔"
GitNotStaged   = "✎"
GitConflicted  = "✼"
GitUntracked   = "…"


[theme]
Separator         = { fg =   15 }
Username          = { fg =  234, bg =  250}
UsernameRoot      = { fg =  234, bg =  198}
Hostname          = { fg =  234, bg =  252}
Home              = { fg =   30, bg =   15}
Path              = { fg =  234, bg =  254}
Cwd               = { fg =  236, bg =  254}
Readonly          = { fg =  124, bg =  253}
Ssh               = { fg =  166, bg =  254}
DockerMachine     = { fg =   55, bg =  177}
KubeCluster       = { fg =  117, bg =   26}
KubeNamespace     = { fg =  170, bg =   17}
DotEnv            = { fg =   15, bg =   55}
 # Aws              = { fg  = ?, bg = ?}
RepoClean         = { fg =  232, bg =  230}
RepoDirty         = { fg =  232, bg =  223}
Jobs              = { fg =  238, bg =   39}
CmdPassed         = { fg =   18, bg =    7}
CmdFailed         = { fg =  254, bg =  124}
SvnChanges        = { fg =  148, bg =   22}
GitAhead          = { fg =  240, bg =  250}
GitBehind         = { fg =  240, bg =  251}
GitStaged         = { fg =   22, bg =   15}
GitNotStaged      = { fg =  130, bg =   15}
GitUntracked      = { fg =   52, bg =   15}
GitConflicted     = { fg =    9, bg =   15}
GitStashed        = { fg =   15, bg =   20}
VirtualEnv        = { fg =   35, bg =  254}
VirtualGo         = { fg =   35, bg =  254}
Perlbrew          = { fg =   20, bg =   15}
TFWs              = { fg =   15, bg =   26}
Time              = { fg =  236, bg =  15}
# ShellVar          = { fg =  ?, bg = ?}
# Node              = { fg =  ?, bg = ?}
Load              = { fg =   15, bg =   22}
NixShell          = { fg =   69, bg =  254}
# Duration          = { fg =  ?, bg = ?}
