args:
    GitMode : simple
    CwdMode : simple
    CwdMaxDepth : 0
    CwdMaxDirSize : 0
    ColorizeHostname : false
    Mode : ""
    Shell : bash
    LeftSegments : [user, host, ssh, perms, pwd, git, jobs, root, exit]
    MaxWidthPercentage : 0
    TruncateSegmentWidth : 0
    PrevError : 0
    NumericExitCodes : false
    IgnoreRepos : ""
    ShortenGKENames : false
    PathAliases : ""
    Duration : ""
    TermWidth : 0

symbols:
    Lock :           "\uE0A2"
    Network :        "\uE0A2"
    Separator :      "\uE0B0"
    SeparatorThin :  "\uE0B1"
    GitBranch :      "\uE0A0"
    GitDetached :    "\u27A6"
    GitAhead :       "\u2B06"
    GitBehind :      "\u2B07"
    GitStaged :      "\u2714"
    GitNotStaged :   "\u270E"
    GitConflicted :  "\u273C"
    GitUntracked :   "\u2026"

theme :
    Separator :     { fg : 15 }
    Username :      { fg : 250 , bg : 240}
    UsernameRoot :  { fg : 250 , bg : 124}
    Hostname :      { fg : 250 , bg : 238}
    Home :          { fg : 15  , bg : 31}
    Path :          { fg : 250 , bg : 237}
    Cwd :           { fg : 254 , bg : 237}
    Readonly :      { fg : 254 , bg : 124}
    Ssh :           { fg : 254 , bg : 166}
    DockerMachine : { fg : 177 , bg : 55}
    KubeCluster :   { fg : 117 , bg : 26}
    KubeNamespace : { fg : 170 , bg : 17}
    DotEnv :        { fg : 15  , bg : 55}
    Aws :           { fg : 15  , bg : 22}
    RepoClean :     { fg : 0   , bg : 148}
    RepoDirty :     { fg : 15  , bg : 161}
    Jobs :          { fg : 39  , bg : 238}
    CmdPassed :     { fg : 15  , bg : 236}
    CmdFailed :     { fg : 15  , bg : 161}
    SvnChanges :    { fg : 22  , bg : 148}
    GitAhead :      { fg : 250 , bg : 240}
    GitBehind :     { fg : 250 , bg : 240}
    GitStaged :     { fg : 15  , bg : 22}
    GitNotStaged :  { fg : 15  , bg : 130}
    GitUntracked :  { fg : 15  , bg : 52}
    GitConflicted : { fg : 15  , bg : 9}
    GitStashed :    { fg : 15  , bg : 20}
    VirtualEnv :    { fg : 0   , bg : 35}
    VirtualGo :     { fg : 0   , bg : 35}
    Perlbrew :      { fg : 0   , bg : 20}
    TFWs :          { fg : 15  , bg : 26}
    Time :          { fg : 15  , bg : 236}
    ShellVar :      { fg : 52  , bg : 11}
    Node :          { fg : 15  , bg : 40}
    Load :          { fg : 15  , bg : 22}
    NixShell :      { fg : 0   , bg : 69}
    Duration :      { fg : 250 , bg : 237}
