[args]
left_segments    = ["user","host","pwd","shell"]
right_segments   = ["time", "git", "exit", "root"]
down_segments = []

timeout = 1000

width_limit    = 0
padding_left   = 1
padding_right  = 1
padding_end    = 1

force_newline  = false
native_rprompt = false

numeric_status  = false
jobs_count    = true

default_user = ""
default_host = ""
time_format  = "%T"

dir_fancy   = false
dir_depth   = 0
dir_length = 0

git_format  = "@.><+!?x"
git_fancy   = true
git_count   = true
git_ignore  = {}

path_aliases = {}


[symbols]
separator   = "" # "\uE0B0"
separator2  = "" # "\uE0B1"
rseparator  = "" # "\uE0B2"
rseparator2 = "" # "\uE0B3"
    
top_prefix = ""
bot_prefix = ""
    
home     = "~"
prompt   = ">"
root     = "#"
host     = "@"
jobs     = "…"
node     = "⬢"
readonly = " ⃠" # "\u20E0"
dir_wrap = "…"  # "\u2026"

git_branch   = ""  # ""
git_dirty    = "✳"
git_hash     = "#" # ""
git_tag      = "&" # ""
git_stash    = "✳" # "⚑"
git_ahead    = "↑" # ""
git_behind   = "↓" # ""
git_staged   = "+" # ""
git_nstaged  = "!" # "✎"
git_conflicted = "×" # "×"
git_untracked  = "?" # "…"


[theme]
 separator      = {fg = -1, bg = -1}
 exit_success   = {fg = -1, bg = -1}
 exit_failure   = {fg = -1, bg = -1}

 username       = {fg = -1, bg = -1}
 root           = {fg = -1, bg = -1}
 hostname       = {fg = -1, bg = -1}
 home           = {fg = -1, bg = -1}
 path           = {fg = -1, bg = -1}
 dir            = {fg = -1, bg = -1}
 readonly       = {fg = -1, bg = -1}

 ssh            = {fg = -1, bg = -1}
 docker         = {fg = -1, bg = -1}
 dot_env        = {fg = -1, bg = -1}
 aws            = {fg = -1, bg = -1}
 jobs           = {fg = -1, bg = -1}
 virtual_env    = {fg = -1, bg = -1}
 time           = {fg = -1, bg = -1}
 duration       = {fg = -1, bg = -1}

 git_clean      = {fg = -1, bg = -1}
 git_dirty      = {fg = -1, bg = -1}
 git_stash      = {fg = -1, bg = -1}
 git_ahead      = {fg = -1, bg = -1}
 git_behind     = {fg = -1, bg = -1}
 git_staged     = {fg = -1, bg = -1}
 git_nstaged    = {fg = -1, bg = -1}
 git_untracked  = {fg = -1, bg = -1}
 git_conflicted = {fg = -1, bg = -1}
