segments.left  = ['dir', 'git', 'hg', 'venv']
segments.right = ['time','status','jobs','perms','root']
segments.down  = ['shell']

global.symbol.separator      = ''
global.symbol.separator2     = ''
global.symbol.rseparator     = ''
global.symbol.rseparator2    = ''

global.padding.left  = 1
global.padding.right = 1
global.padding.end   = 0

user.default  = 'nitoref'
user.theme    = {fg = 240}

shell.symbol.bash   = '❯'
shell.theme.success = {fg = 212}
shell.theme.failure = {fg = 197}

status.theme.success   = {fg = 212}
status.theme.failure   = {fg = 197}

dir.fancy = false
dir.depth = 3
dir.theme.home  = {fg = 74}
dir.theme.path  = {fg = 223}
dir.theme.cwd   = {fg = 223}
dir.symbol.wrap = '…'
dir.alias = [
	{'/usr/local/Cellar' = 'cellar'},
	{'Documents' = ''}
]

perms.symbol.readonly = ' '
perms.theme.readonly  = {fg = 209}


root.symbol= ' '
root.theme = {fg = 230}

jobs.symbol = ' '
jobs.count  = false


# git.template  = '@%.?!'
git.fancy     = false
git.count     = false

git.symbol.branch     = ''
git.symbol.hash       = '#'
git.symbol.tag        = '&'
git.symbol.stash      = '*'
git.symbol.ahead      = '⇡'
git.symbol.behind     = '⇣'
git.symbol.staged     = '+'
git.symbol.notstaged  = '!'
git.symbol.conflicted = '×'
git.symbol.untracked  = '?'
git.theme.clean  = {fg = 242}
git.theme.dirty  = {fg = 250}
git.theme.stash  = {fg = 76}
git.theme.ahead  = {fg = 159}
git.theme.behind = {fg = 240}
git.theme.staged = {fg = 220}
git.theme.notstaged  = {fg = 213}
git.theme.untracked  = {fg = 51}
git.theme.conflicted = {fg =  9}

host.theme = {fg = 240}

time.template = '%H:%M:%S  %d/%m/%y'
time.theme  = {fg = 244}

jobs.theme        = {fg = 151}
ssh.theme         = {fg = 166}
aws.theme         = {fg = 22}
docker.theme      = {fg = 55}
dot_env.theme     = {fg = 55}
duration.theme    = {fg = 237}

venv.symbol = 'py'
venv.theme = {fg = 35}

[[extension]]
name = "yolk"
cmd = "echo yolk"
env = "BAR"
theme = {bg = 25, fg = 230}
