[segments]
left = [
  'dir',
  'git'
]
right = [
  'time',
  'host',
  'status',
  'perms',
  'root',
  'jobs',
]
down = [
  'shell'
]

[args]
padding_left  = 1
padding_right = 1
padding_end   = 0
default_user  = 'nitoref'
jobs_count    = false
time_format   = '%H:%M:%S'
git_format    = '@d'
git_fancy     = false
git_count     = false
dir_fancy     = false
dir_depth     = 3

[symbols]
readonly       = ''
root           = ' '
jobs           = ' '
prompt         = '❯'
dir_wrap       = '…'
separator      = ''
separator2     = ''
rseparator     = ''
rseparator2    = ''
git_branch     = ''
git_hash       = '#'
git_tag        = '&'
git_stash      = '*'
git_ahead      = '⇡'
git_behind     = '⇣'
git_staged     = '+'
git_nstaged    = '!'
git_conflicted = '×'
git_untracked  = '?'

[theme]
exit_success   = {fg = 212}
exit_failure   = {fg = 197}

username = {fg = 240}
root     = {fg = 230}
hostname = {fg = 240}
home     = {fg = 74}
path     = {fg = 223}
dir      = {fg = 223}
readonly = {fg = 209}

time        = {fg = 244}
jobs        = {fg = 151}
ssh         = {fg = 166}
aws         = {fg = 22}
docker      = {fg = 55}
dot_env     = {fg = 55}
virtual_env = {fg = 35}
duration    = {fg = 237}

git_clean  = {fg = 250}
git_dirty  = {fg = 242}
git_stash  = {fg = 76}
git_ahead  = {fg = 159}
git_behind = {fg = 240}
git_staged = {fg = 113}
git_nstaged    = {fg = 11}
git_untracked  = {fg = 14}
git_conflicted = {fg =  9}

[[extension]]
name = "yolk"
command = "echo yolk"
style = {bg = 25, fg = 230}
