segments.left = [
  'dir',
  'perms',
  'root',
  'shell',
  'ssh',
  'aws',
  'docker',
  'venv',
  'load',
]
segments.right = [
  'time',
  'context',
  'jobs',
  'git',
  'hg',
  'status',
]

global.width_limit = 0.7
# global.symbol.separator2     = ''
# global.symbol.rseparator2    = ''
global.padding_left = 1
global.padding_right = 1
global.padding_end = 1

jobs.count = true
time.format = '%H:%M:%S'

# dir.fancy = true
dir.depth = 3
dir.alias = [
  {'Documents' = ''}
]


dir.symbol.wrap  = '…'
host.symbol      = '@'
root.symbol      = ''
jobs.symbol      = ''
shell.symbol     = '$'

global.theme.separator   = {fg = 254}
status.theme.success     = {fg = 254, bg = 235}
status.theme.failure     = {fg = 254, bg = 160}
perms.theme.readonly = {fg = 166}
dir.theme.home = {fg = 254, bg = 61}
dir.theme.path = {fg = 254, bg = 61}
dir.theme.cwd  = {fg = 230, bg = 61}
user.theme     = {fg = 254}
root.theme     = {fg = 37}
host.theme     = {fg = 248, bg = 234}
jobs.theme     = {fg = 136, bg = 235}
ssh.theme      = {fg = 8,   bg = 9}
docker.theme   = {fg = 13,  bg = 55}
venv.theme     = {fg = 8,   bg = 6}

hg.symbol.branch = ' '

git.symbol.branch     = ''
git.symbol.hash       = ''
git.symbol.tag        = ''
git.symbol.stash      = '⚑'
git.symbol.ahead      = ''
git.symbol.behind     = ''
git.symbol.staged     = ''
git.symbol.notstaged  = '✎'
git.symbol.conflicted = '×'
git.symbol.untracked  = ''

git.theme.clean      = {fg = 64, bg = 230}
git.theme.dirty      = {fg = 125, bg = 230}
git.theme.stash      = {fg = 33,  bg = 230}
git.theme.ahead      = {fg = 37,  bg = 230}
git.theme.behind     = {fg = 37,  bg = 230}
git.theme.staged     = {fg = 64,  bg = 230}
git.theme.notstaged  = {fg = 160, bg = 230}
git.theme.untracked  = {fg = 136, bg = 230}
git.theme.conflicted = {fg = 166, bg = 230}
git.theme.ignored    = {fg = 166, bg = 230}
# git.ignore = ["/Users/nitoref/freebsd-ports/"]