segments.left = [
  'perms',
  'root',
  'dir',
  'shell',
  'ssh',
  'aws',
  'docker',
  'venv',
]
segments.right = [
  'time',
  'host',
  'load',
  # 'jobs',
  'git',
  'hg',
  'status',
]

global.width_limit = 0.7
# global.symbol.separator2     = ''
# global.symbol.rseparator2    = ''
global.padding_left = 1
global.padding_right = 1
global.padding_end = 1

jobs.count = true
time.format = '%H:%M:%S'

# dir.fancy = true
dir.depth = 3
dir.alias = [
  {'Documents' = ''}
]


shell.theme.success = {bg = 0}
shell.theme.failure = {fg = 9, bg = 0}

perms.symbol.readonly = ''

dir.symbol.wrap  = '…'
host.symbol      = '@'
root.symbol      = ''
jobs.symbol      = ''
shell.symbol     = '$'

global.theme.separator   = {fg = 240, bg = 0}
status.theme.success     = {fg = 254, bg = 0}
status.theme.failure     = {fg = 9, bg = 0}
perms.theme.readonly = {fg = 166, bg = 0}
dir.theme.home = {fg = 11, bg = 0}
dir.theme.path = {fg = 11, bg = 0}
dir.theme.cwd  = {fg = 14, bg = 0}
user.theme     = {fg = 254, bg = 0}
root.theme     = {fg = 37, bg = 0}
host.theme     = {bg = 0}
jobs.theme     = {fg = 136, bg = 0}
ssh.theme      = {fg = 8,   bg = 0}
docker.theme   = {fg = 13,  bg = 0}
venv.theme     = {fg = 8,   bg = 0}
time.theme     = {fg = 248, bg = 0}
load.theme     = {fg = 9, bg = 0}

hg.symbol.branch = ' '

git.symbol.branch     = ''
git.symbol.hash       = ' '
git.symbol.tag        = ' '
git.symbol.stash      = ' *'
git.symbol.ahead      = ' ↑'
git.symbol.behind     = ' ↓'
git.symbol.staged     = ' ✔'
git.symbol.notstaged  = ' ✎'
git.symbol.conflicted = ' ×'
git.symbol.untracked  = ' ?'

git.theme.clean      = {fg = 6,   bg = 0}
git.theme.dirty      = {fg = 3,   bg = 0}
git.theme.ignored    = {bg = 14}
git.theme.stash      = {bg = 0}
git.theme.ahead      = {bg = 0}
git.theme.behind     = {bg = 0}
git.theme.staged     = {bg = 0}
git.theme.notstaged  = {bg = 0}
git.theme.untracked  = {bg = 0}
git.theme.conflicted = {bg = 0}
# git.ignore = ["/Users/nitoref/freebsd-ports/"]