segments.left = [
  'perms',
  'root',
  'shell'
]
segments.right = [
  'time',
  'host',
  'user',
  'jobs',
  'dir',
  'git',
  'status'
]

global.force_newline  = false
global.native_rprompt = false
global.padding.left   = 1
global.padding.right  = 1
global.padding.end    = 1
global.symbol.separator   = ''
global.symbol.separator2  = ''
global.symbol.rseparator  = ''
global.symbol.rseparator2 = ''
global.symbol.top_prefix  = ''
global.symbol.bot_prefix  = ''
global.theme.separator  = {fg = 254}
global.theme.background = {fg = 254}

context.default = ""
context.template = "u@h"
context.always = false
context.theme.default = {fg = 248}
context.theme.root = {fg = 248}

user.default       = 'nitoref'
user.theme.default = {fg = 254}
user.theme.root    = {fg = 37}
user.always        = false

host.default  = ""
host.symbol   = "@"
host.template = "u@h"
host.always   = false
host.theme    = {fg = 248}

dir.theme.home   = {fg = 230, bg = 61}
dir.theme.path   = {fg = 254, bg = 61}
dir.theme.cwd    = {fg = 230, bg = 61}
dir.symbol.wrap  = '…'
dir.symbol.home  = '~'
dir.fancy  = true
dir.depth  = 0
dir.length = 0

perms.theme.readonly  = {fg = 166}
perms.symbol.readonly = " ⃠"

aws.theme    = {fg = -1, bg = -1}

docker.theme = {fg = 13,  bg = 55}


git.symbol.branch     = ''
git.symbol.hash       = ''
git.symbol.tag        = ''
git.symbol.stash      = '⚑'
git.symbol.ahead      = ''
git.symbol.behind     = ''
git.symbol.staged     = ''
git.symbol.notstaged  = '✎'
git.symbol.untracked  = '…'
git.symbol.conflicted = '×'
git.theme.clean      = {fg = 254, bg = 64}
git.theme.dirty      = {fg = 254, bg = 125}
git.theme.stash      = {fg = 33,  bg = 230}
git.theme.ahead      = {fg = 37,  bg = 230}
git.theme.behind     = {fg = 37,  bg = 230}
git.theme.staged     = {fg = 64,  bg = 230}
git.theme.notstaged  = {fg = 160, bg = 230}
git.theme.untracked  = {fg = 136, bg = 230}
git.theme.conflicted = {fg = 166, bg = 230}
git.fancy = true
git.count = true
git.template = ""
git.ignore   = []

jobs.symbol = ''
jobs.verbose = true
jobs.always  = false
jobs.theme.default = {fg = 136, bg = 235}
jobs.theme.none    = {fg = 136, bg = 235}

root.theme  = {fg = 37}
root.symbol = ''

status.numeric = false
status.symbol.success  = false
status.symbol.failure  = false
status.theme.success = {fg = 254, bg = 235}
status.theme.failure = {fg = 254, bg = 160}


venv.theme = {fg = 8,   bg = 6}


prompt.symbol = '$'
prompt.theme.success = {fg = -1, bg = -1}
prompt.theme.failure = {fg = -1, bg = 160}

time.theme    = {fg = 252}
time.template = '%H:%M:%S'

ssh.theme = {fg = 8,   bg = 9}

