#ifndef COLOR_H
#define COLOR_H

#include <unordered_map>

enum class font: uint8_t
{
	bold = 1,
	faint = 2,
	italic = 3,
	underline = 4,
	blink = 5,
	rblink = 6,
	reversed = 7,
	conceal = 8,
	crossed = 9
}

enum class color: uint8_t
{
	black = 0,
	red = 1,
	green = 2,
	yellow = 3,
	blue = 4,
	magenta = 5,
	cyan = 6,
	white = 7,
	grey = 8,
	maroon = 9,
	lime = 10,
	olive = 11,
	navy = 12,
	fuchsia = 13,
	purple = 13,
	aqua = 14,
	teal = 14,
	silver = 15,
	grey0 = 16,
	navyblue = 17,
	darkblue = 18,
	blue3 = 19,
	blue3 = 20,
	blue1 = 21,
	darkgreen = 22,
	deepskyblue4 = 23,
	deepskyblue4 = 24,
	deepskyblue4 = 25,
	dodgerblue3 = 26,
	dodgerblue2 = 27,
	green4 = 28,
	springgreen4 = 29,
	turquoise4 = 30,
	deepskyblue3 = 31,
	deepskyblue3 = 32,
	dodgerblue1 = 33,
	green3 = 34,
	springgreen3 = 35,
	darkcyan = 36,
	lightseagreen = 37,
	deepskyblue2 = 38,
	deepskyblue1 = 39,
	green3 = 40,
	springgreen3 = 41,
	springgreen2 = 42,
	cyan3 = 43,
	darkturquoise = 44,
	turquoise2 = 45,
	green1 = 46,
	springgreen2 = 47,
	springgreen1 = 48,
	mediumspringgreen = 49,
	cyan2 = 50,
	cyan1 = 51,
	darkred = 52,
	deeppink4 = 53,
	purple4 = 54,
	purple4 = 55,
	purple3 = 56,
	blueviolet = 57,
	orange4 = 58,
	grey37 = 59,
	mediumpurple4 = 60,
	slateblue3 = 61,
	slateblue3 = 62,
	royalblue1 = 63,
	chartreuse4 = 64,
	darkseagreen4 = 65,
	paleturquoise4 = 66,
	steelblue = 67,
	steelblue3 = 68,
	cornflowerblue = 69,
	chartreuse3 = 70,
	darkseagreen4 = 71,
	cadetblue = 72,
	cadetblue = 73,
	skyblue3 = 74,
	steelblue1 = 75,
	chartreuse3 = 76,
	palegreen3 = 77,
	seagreen3 = 78,
	aquamarine3 = 79,
	mediumturquoise = 80,
	steelblue1 = 81,
	chartreuse2 = 82,
	seagreen2 = 83,
	seagreen1 = 84,
	seagreen1 = 85,
	aquamarine1 = 86,
	darkslategray2 = 87,
	darkred = 88,
	deeppink4 = 89,
	darkmagenta = 90,
	darkmagenta = 91,
	darkviolet = 92,
	purple = 93,
	orange4 = 94,
	lightpink4 = 95,
	plum4 = 96,
	mediumpurple3 = 97,
	mediumpurple3 = 98,
	slateblue1 = 99,
	yellow4 = 100,
	wheat4 = 101,
	grey53 = 102,
	lightslategrey = 103,
	mediumpurple = 104,
	lightslateblue = 105,
	yellow4 = 106,
	darkolivegreen3 = 107,
	darkseagreen = 108,
	lightskyblue3 = 109,
	lightskyblue3 = 110,
	skyblue2 = 111,
	chartreuse2 = 112,
	darkolivegreen3 = 113,
	palegreen3 = 114,
	darkseagreen3 = 115,
	darkslategray3 = 116,
	skyblue1 = 117,
	chartreuse1 = 118,
	lightgreen = 119,
	lightgreen = 120,
	palegreen1 = 121,
	aquamarine1 = 122,
	darkslategray1 = 123,
	red3 = 124,
	deeppink4 = 125,
	mediumvioletred = 126,
	magenta3 = 127,
	darkviolet = 128,
	purple = 129,
	darkorange3 = 130,
	indianred = 131,
	hotpink3 = 132,
	mediumorchid3 = 133,
	mediumorchid = 134,
	mediumpurple2 = 135,
	darkgoldenrod = 136,
	lightsalmon3 = 137,
	rosybrown = 138,
	grey63 = 139,
	mediumpurple2 = 140,
	mediumpurple1 = 141,
	gold3 = 142,
	darkkhaki = 143,
	navajowhite3 = 144,
	grey69 = 145,
	lightsteelblue3 = 146,
	lightsteelblue = 147,
	yellow3 = 148,
	darkolivegreen3 = 149,
	darkseagreen3 = 150,
	darkseagreen2 = 151,
	lightcyan3 = 152,
	lightskyblue1 = 153,
	greenyellow = 154,
	darkolivegreen2 = 155,
	palegreen1 = 156,
	darkseagreen2 = 157,
	darkseagreen1 = 158,
	paleturquoise1 = 159,
	red3 = 160,
	deeppink3 = 161,
	deeppink3 = 162,
	magenta3 = 163,
	magenta3 = 164,
	magenta2 = 165,
	darkorange3 = 166,
	indianred = 167,
	hotpink3 = 168,
	hotpink2 = 169,
	orchid = 170,
	mediumorchid1 = 171,
	orange3 = 172,
	lightsalmon3 = 173,
	lightpink3 = 174,
	pink3 = 175,
	plum3 = 176,
	violet = 177,
	gold3 = 178,
	lightgoldenrod3 = 179,
	tan = 180,
	mistyrose3 = 181,
	thistle3 = 182,
	plum2 = 183,
	yellow3 = 184,
	khaki3 = 185,
	lightgoldenrod2 = 186,
	lightyellow3 = 187,
	grey84 = 188,
	lightsteelblue1 = 189,
	yellow2 = 190,
	darkolivegreen1 = 191,
	darkolivegreen1 = 192,
	darkseagreen1 = 193,
	honeydew2 = 194,
	lightcyan1 = 195,
	red1 = 196,
	deeppink2 = 197,
	deeppink1 = 198,
	deeppink1 = 199,
	magenta2 = 200,
	magenta1 = 201,
	orangered1 = 202,
	indianred1 = 203,
	indianred1 = 204,
	hotpink = 205,
	hotpink = 206,
	mediumorchid1 = 207,
	darkorange = 208,
	salmon1 = 209,
	lightcoral = 210,
	palevioletred1 = 211,
	orchid2 = 212,
	orchid1 = 213,
	orange1 = 214,
	sandybrown = 215,
	lightsalmon1 = 216,
	lightpink1 = 217,
	pink1 = 218,
	plum1 = 219,
	gold1 = 220,
	lightgoldenrod2 = 221,
	lightgoldenrod2 = 222,
	navajowhite1 = 223,
	mistyrose1 = 224,
	thistle1 = 225,
	yellow1 = 226,
	lightgoldenrod1 = 227,
	khaki1 = 228,
	wheat1 = 229,
	cornsilk1 = 230,
	grey100 = 231,
	grey3 = 232,
	grey7 = 233,
	grey11 = 234,
	grey15 = 235,
	grey19 = 236,
	grey23 = 237,
	grey27 = 238,
	grey30 = 239,
	grey35 = 240,
	grey39 = 241,
	grey42 = 242,
	grey46 = 243,
	grey50 = 244,
	grey54 = 245,
	grey58 = 246,
	grey62 = 247,
	grey66 = 248,
	grey70 = 249,
	grey74 = 250,
	grey78 = 251,
	grey82 = 252,
	grey85 = 253,
	grey89 = 254,
	grey93 = 255
}

color from (std::string s) {
	std::unordered_map<std::string, color> map {
		{"black", color::black},
		{"red", color::red},
		{"green", color::green},
		{"yellow", color::yellow},
		{"blue", color::blue},
		{"magenta", color::magenta},
		{"cyan", color::cyan},
		{"white", color::white},
		{"grey", color::grey},
		{"maroon", color::maroon},
		{"lime", color::lime},
		{"olive", color::olive},
		{"navy", color::navy},
		{"fuchsia", color::fuchsia},
		{"purple", color::purple},
		{"aqua", color::aqua},
		{"teal", color::teal},
		{"silver", color::silver},
		{"grey0", color::grey0},
		{"navyblue", color::navyblue},
		{"darkblue", color::darkblue},
		{"blue3", color::blue3},
		{"blue3", color::blue3},
		{"blue1", color::blue1},
		{"darkgreen", color::darkgreen},
		{"deepskyblue4", color::deepskyblue4},
		{"deepskyblue4", color::deepskyblue4},
		{"deepskyblue4", color::deepskyblue4},
		{"dodgerblue3", color::dodgerblue3},
		{"dodgerblue2", color::dodgerblue2},
		{"green4", color::green4},
		{"springgreen4", color::springgreen4},
		{"turquoise4", color::turquoise4},
		{"deepskyblue3", color::deepskyblue3},
		{"deepskyblue3", color::deepskyblue3},
		{"dodgerblue1", color::dodgerblue1},
		{"green3", color::green3},
		{"springgreen3", color::springgreen3},
		{"darkcyan", color::darkcyan},
		{"lightseagreen", color::lightseagreen},
		{"deepskyblue2", color::deepskyblue2},
		{"deepskyblue1", color::deepskyblue1},
		{"green3", color::green3},
		{"springgreen3", color::springgreen3},
		{"springgreen2", color::springgreen2},
		{"cyan3", color::cyan3},
		{"darkturquoise", color::darkturquoise},
		{"turquoise2", color::turquoise2},
		{"green1", color::green1},
		{"springgreen2", color::springgreen2},
		{"springgreen1", color::springgreen1},
		{"mediumspringgreen", color::mediumspringgreen},
		{"cyan2", color::cyan2},
		{"cyan1", color::cyan1},
		{"darkred", color::darkred},
		{"deeppink4", color::deeppink4},
		{"purple4", color::purple4},
		{"purple4", color::purple4},
		{"purple3", color::purple3},
		{"blueviolet", color::blueviolet},
		{"orange4", color::orange4},
		{"grey37", color::grey37},
		{"mediumpurple4", color::mediumpurple4},
		{"slateblue3", color::slateblue3},
		{"slateblue3", color::slateblue3},
		{"royalblue1", color::royalblue1},
		{"chartreuse4", color::chartreuse4},
		{"darkseagreen4", color::darkseagreen4},
		{"paleturquoise4", color::paleturquoise4},
		{"steelblue", color::steelblue},
		{"steelblue3", color::steelblue3},
		{"cornflowerblue", color::cornflowerblue},
		{"chartreuse3", color::chartreuse3},
		{"darkseagreen4", color::darkseagreen4},
		{"cadetblue", color::cadetblue},
		{"cadetblue", color::cadetblue},
		{"skyblue3", color::skyblue3},
		{"steelblue1", color::steelblue1},
		{"chartreuse3", color::chartreuse3},
		{"palegreen3", color::palegreen3},
		{"seagreen3", color::seagreen3},
		{"aquamarine3", color::aquamarine3},
		{"mediumturquoise", color::mediumturquoise},
		{"steelblue1", color::steelblue1},
		{"chartreuse2", color::chartreuse2},
		{"seagreen2", color::seagreen2},
		{"seagreen1", color::seagreen1},
		{"seagreen1", color::seagreen1},
		{"aquamarine1", color::aquamarine1},
		{"darkslategray2", color::darkslategray2},
		{"darkred", color::darkred},
		{"deeppink4", color::deeppink4},
		{"darkmagenta", color::darkmagenta},
		{"darkmagenta", color::darkmagenta},
		{"darkviolet", color::darkviolet},
		{"purple", color::purple},
		{"orange4", color::orange4},
		{"lightpink4", color::lightpink4},
		{"plum4", color::plum4},
		{"mediumpurple3", color::mediumpurple3},
		{"mediumpurple3", color::mediumpurple3},
		{"slateblue1", color::slateblue1},
		{"yellow4", color::yellow4},
		{"wheat4", color::wheat4},
		{"grey53", color::grey53},
		{"lightslategrey", color::lightslategrey},
		{"mediumpurple", color::mediumpurple},
		{"lightslateblue", color::lightslateblue},
		{"yellow4", color::yellow4},
		{"darkolivegreen3", color::darkolivegreen3},
		{"darkseagreen", color::darkseagreen},
		{"lightskyblue3", color::lightskyblue3},
		{"lightskyblue3", color::lightskyblue3},
		{"skyblue2", color::skyblue2},
		{"chartreuse2", color::chartreuse2},
		{"darkolivegreen3", color::darkolivegreen3},
		{"palegreen3", color::palegreen3},
		{"darkseagreen3", color::darkseagreen3},
		{"darkslategray3", color::darkslategray3},
		{"skyblue1", color::skyblue1},
		{"chartreuse1", color::chartreuse1},
		{"lightgreen", color::lightgreen},
		{"lightgreen", color::lightgreen},
		{"palegreen1", color::palegreen1},
		{"aquamarine1", color::aquamarine1},
		{"darkslategray1", color::darkslategray1},
		{"red3", color::red3},
		{"deeppink4", color::deeppink4},
		{"mediumvioletred", color::mediumvioletred},
		{"magenta3", color::magenta3},
		{"darkviolet", color::darkviolet},
		{"purple", color::purple},
		{"darkorange3", color::darkorange3},
		{"indianred", color::indianred},
		{"hotpink3", color::hotpink3},
		{"mediumorchid3", color::mediumorchid3},
		{"mediumorchid", color::mediumorchid},
		{"mediumpurple2", color::mediumpurple2},
		{"darkgoldenrod", color::darkgoldenrod},
		{"lightsalmon3", color::lightsalmon3},
		{"rosybrown", color::rosybrown},
		{"grey63", color::grey63},
		{"mediumpurple2", color::mediumpurple2},
		{"mediumpurple1", color::mediumpurple1},
		{"gold3", color::gold3},
		{"darkkhaki", color::darkkhaki},
		{"navajowhite3", color::navajowhite3},
		{"grey69", color::grey69},
		{"lightsteelblue3", color::lightsteelblue3},
		{"lightsteelblue", color::lightsteelblue},
		{"yellow3", color::yellow3},
		{"darkolivegreen3", color::darkolivegreen3},
		{"darkseagreen3", color::darkseagreen3},
		{"darkseagreen2", color::darkseagreen2},
		{"lightcyan3", color::lightcyan3},
		{"lightskyblue1", color::lightskyblue1},
		{"greenyellow", color::greenyellow},
		{"darkolivegreen2", color::darkolivegreen2},
		{"palegreen1", color::palegreen1},
		{"darkseagreen2", color::darkseagreen2},
		{"darkseagreen1", color::darkseagreen1},
		{"paleturquoise1", color::paleturquoise1},
		{"red3", color::red3},
		{"deeppink3", color::deeppink3},
		{"deeppink3", color::deeppink3},
		{"magenta3", color::magenta3},
		{"magenta3", color::magenta3},
		{"magenta2", color::magenta2},
		{"darkorange3", color::darkorange3},
		{"indianred", color::indianred},
		{"hotpink3", color::hotpink3},
		{"hotpink2", color::hotpink2},
		{"orchid", color::orchid},
		{"mediumorchid1", color::mediumorchid1},
		{"orange3", color::orange3},
		{"lightsalmon3", color::lightsalmon3},
		{"lightpink3", color::lightpink3},
		{"pink3", color::pink3},
		{"plum3", color::plum3},
		{"violet", color::violet},
		{"gold3", color::gold3},
		{"lightgoldenrod3", color::lightgoldenrod3},
		{"tan", color::tan},
		{"mistyrose3", color::mistyrose3},
		{"thistle3", color::thistle3},
		{"plum2", color::plum2},
		{"yellow3", color::yellow3},
		{"khaki3", color::khaki3},
		{"lightgoldenrod2", color::lightgoldenrod2},
		{"lightyellow3", color::lightyellow3},
		{"grey84", color::grey84},
		{"lightsteelblue1", color::lightsteelblue1},
		{"yellow2", color::yellow2},
		{"darkolivegreen1", color::darkolivegreen1},
		{"darkolivegreen1", color::darkolivegreen1},
		{"darkseagreen1", color::darkseagreen1},
		{"honeydew2", color::honeydew2},
		{"lightcyan1", color::lightcyan1},
		{"red1", color::red1},
		{"deeppink2", color::deeppink2},
		{"deeppink1", color::deeppink1},
		{"deeppink1", color::deeppink1},
		{"magenta2", color::magenta2},
		{"magenta1", color::magenta1},
		{"orangered1", color::orangered1},
		{"indianred1", color::indianred1},
		{"indianred1", color::indianred1},
		{"hotpink", color::hotpink},
		{"hotpink", color::hotpink},
		{"mediumorchid1", color::mediumorchid1},
		{"darkorange", color::darkorange},
		{"salmon1", color::salmon1},
		{"lightcoral", color::lightcoral},
		{"palevioletred1", color::palevioletred1},
		{"orchid2", color::orchid2},
		{"orchid1", color::orchid1},
		{"orange1", color::orange1},
		{"sandybrown", color::sandybrown},
		{"lightsalmon1", color::lightsalmon1},
		{"lightpink1", color::lightpink1},
		{"pink1", color::pink1},
		{"plum1", color::plum1},
		{"gold1", color::gold1},
		{"lightgoldenrod2", color::lightgoldenrod2},
		{"lightgoldenrod2", color::lightgoldenrod2},
		{"navajowhite1", color::navajowhite1},
		{"mistyrose1", color::mistyrose1},
		{"thistle1", color::thistle1},
		{"yellow1", color::yellow1},
		{"lightgoldenrod1", color::lightgoldenrod1},
		{"khaki1", color::khaki1},
		{"wheat1", color::wheat1},
		{"cornsilk1", color::cornsilk1},
		{"grey100", color::grey100},
		{"grey3", color::grey3},
		{"grey7", color::grey7},
		{"grey11", color::grey11},
		{"grey15", color::grey15},
		{"grey19", color::grey19},
		{"grey23", color::grey23},
		{"grey27", color::grey27},
		{"grey30", color::grey30},
		{"grey35", color::grey35},
		{"grey39", color::grey39},
		{"grey42", color::grey42},
		{"grey46", color::grey46},
		{"grey50", color::grey50},
		{"grey54", color::grey54},
		{"grey58", color::grey58},
		{"grey62", color::grey62},
		{"grey66", color::grey66},
		{"grey70", color::grey70},
		{"grey74", color::grey74},
		{"grey78", color::grey78},
		{"grey82", color::grey82},
		{"grey85", color::grey85},
		{"grey89", color::grey89},
		{"grey93", color::grey93},
	}
	return map.at(str);
}

#endif